---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        Optimized for Kindle and iPad
        Almost 9000 pages of content
        Includes a free copy of 1st Edition PDF
    media:
      - ebook
    price: 3500

  -
    code: screencasts
    name: "HTML & Screencasts"
    description:
      |
        Full updated for the 2nd edition
        100% DRM-free digital downloads
        (QuickTime and Ogg Vorbis)
        Includes first edition screencasts
    media:
      - ebook
      - screencasts
    price: 12500

  -
    code: all
    name: "HTML, Ebook, and Screencasts"
    description:
      |
        Includes all 50 screencasts
        eBook formats for Kindle, Nook, and PDF
        Read online.
    media:
      - ebook
      - screencasts
    price: 12500
    regular_price: 19900

authors:
  -
    name: "Robert Mosolgo"
    image: /images/rmosolgo.png
    contact_email: "rdmosolgo@gmail.com"
    bio:
      |
        Robert Mosolgo studied Chinese Studies at [The College of William and Mary](http://wm.edu). He discovered
        web programming while working at [AidData](http://aiddata.org). Now, he enjoys productive and expressive work
        as a developer at [Planning Center Online](http://get.planningcenteronline.com).
        He is also a committer to [batman.js](http://github.com/batmanjs/batman).

        Robert lives in Carlsbad, California with his wife Valerie ([@vwmos](https://twitter.com/vwmos)), who designed the cover for this book.

faq: []
testimonials: []
marketing_content: ''

contact_email: ''
hide_custom_domain_footer: false